# Copyright (C) 2025 Texas Instruments Incorporated - https://www.ti.com/
# SPDX-License-Identifier: Apache-2.0

# Need more memory for larger display (400x300)
CONFIG_HEAP_MEM_POOL_SIZE=65536

# GPIO Driver
CONFIG_GPIO=y

#CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y

CONFIG_LOG_DEFAULT_LEVEL=3
#CONFIG_DISPLAY_LOG_LEVEL_DBG=y

# LVGL should allocate buffers equal to size of display
CONFIG_LV_Z_VDB_SIZE=64

# Default Dot Per Inch. [px/inch]
# Used to initialize default sizes such as widgets sized, style paddings.
CONFIG_LV_DPI_DEF=128

CONFIG_LV_Z_BITS_PER_PIXEL=1

# Use offloaded render thread
CONFIG_LV_Z_FLUSH_THREAD=y
CONFIG_LV_COLOR_DEPTH_1=y
