# Copyright (C) 2025 Texas Instruments Incorporated - https://www.ti.com/
# SPDX-License-Identifier: Apache-2.0

# Need more memory for larger display (400x300)
CONFIG_HEAP_MEM_POOL_SIZE=65536

# GPIO Driver
CONFIG_GPIO=y

#CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y

CONFIG_LOG_DEFAULT_LEVEL=3
#CONFIG_DISPLAY_LOG_LEVEL_DBG=y